// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");

console.log("Hello, BuckleScript and Reason!");

function unwrap(a, b) {
  if (a.tag) {
    if (b.tag) {
      return a[0] + b[0];
    } else {
      return "foo";
    }
  } else if (a[0] === "foo" && !b.tag) {
    return b[0];
  } else {
    return "foo";
  }
}

console.log(unwrap(/* Left */Block.__(0, ["foo"]), /* Left */Block.__(0, ["x"])));

var x = "foo";

exports.x = x;
exports.unwrap = unwrap;
/*  Not a pure module */
